name: nutrimenu
description: A smart meal planning app that generates menus based on grocery bills
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.5
  
  # Local storage
  shared_preferences: ^2.5.3
  
  # Image handling
  image_picker: ^1.1.2
  
  # HTTP requests for Gemini API
  http: ^1.4.0
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # UI enhancements
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.18.1
  path_provider: ^2.1.5
  
  # For UUID generation
  uuid: ^4.5.1
  
  # For animations and gestures
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.2
  build_runner: ^2.5.2
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  
  # Add assets for the app
  assets:
    - assets/images/
    - assets/patterns/
    - assets/icons/
  
  # Custom fonts for better UI
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700